repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.41.1
    hooks:
    -   id: golangci-lint
-   repo: local
    hooks:
    -   id: go-test
        name: go test
        entry: go test ./...
        language: system
        pass_filenames: false
